
[DEBUG|Properties| segments.py:119|callbackSegments()] Callback called

[DEBUG| Operators|  helpers.py:213|op_logger()] Entering execute() from roboteditor.udpate_model(UpdateModel):

	Nesting Level 1:

	Callstack:
		callbackSegments         		(.../robot_designer_plugin/properties/segments.py:123)
			UpdateModel.run(segment_name=segment_name)
		run                      		(.../robot_designer_plugin/operators/helpers.py:272)


[DEBUG| Operators|  helpers.py:213|op_logger()] Entering execute() from roboteditor.select_segment(SelectSegment):

	Nesting Level 2:

	Callstack:
		callbackSegments         		(.../robot_designer_plugin/properties/segments.py:123)
			UpdateModel.run(segment_name=segment_name)
		run                      		(.../robot_designer_plugin/operators/helpers.py:272)
		execute                  		(.../robot_designer_plugin/operators/segments.py:422)
			SelectSegment.run(segment_name=self.segment_name)
		run                      		(.../robot_designer_plugin/operators/helpers.py:272)


[DEBUG| Operators|  helpers.py:217|op_logger()] Leaving roboteditor.select_segment() SelectSegment({'FINISHED'})

[ERROR| Operators|  helpers.py:287|run()] Exception when running operator roboteditor.udpate_model (UpdateModel):
	keywords:	{'segment_name': 'lowerleg02_L', 'recurse': False, 'model_name': ''}
	Bad keywords:	model_name
	Exception:	TypeError
	Messages:
		Converting py args to operator properties: : keyword "model_name" unrecognized

[ERROR| Operators|  helpers.py:227|op_logger()] Operator roboteditor.udpate_model (UpdateModel) threw an exception:
	Exception:	TypeError
	Messages:
		Converting py args to operator properties: : keyword "model_name" unrecognized

	Nesting Level 1:

	Callstack:
		callbackSegments         		(.../robot_designer_plugin/properties/segments.py:123)
			UpdateModel.run(segment_name=segment_name)
		run                      		(.../robot_designer_plugin/operators/helpers.py:272)


[ERROR| Operators|  helpers.py:295|run()] Exception when running operator roboteditor.udpate_model (UpdateModel):
	Exception:	RuntimeError
	Error: Operator roboteditor.udpate_model (UpdateModel) threw an exception:TypeError
		Converting py args to operator properties: : keyword "model_name" unrecognized